name: Chip8 Logic Tests

on: [push, pull_request]

jobs:
  logic-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Catch2
        run: sudo apt-get update && sudo apt-get install -y catch2
   
      - name: List
        run: sudo find /usr -name "catch.hpp"

      - name: Run Unit Tests
        # Notice we don't need to pass any SDL paths here anymore
        run: make test